### ISSUE TITLE
导出模型挂掉了

### ISSUE THREAD

**Issue by RichieMay** [SelinaFelton/LightFaceNet#1]
在你的百度网盘下载的mobilefacenet的模型，然后用项目中的freeze_graph.py导出挂掉了
saver = tf.train.import_meta_graph(os.path.join(model_dir_exp, meta_file), clear_devices=True) # 这句给出了警告版本old
tf.get_default_session().run(tf.global_variables_initializer())
tf.get_default_session().run(tf.local_variables_initializer()) # 执行到这一步就挂掉了提示tensor没有initializer
TF版本：1.9
python：3.6.5

不知道朋友你是怎么导出来的呢？谢谢

**Comment by ChenyuGAO-CS** [comment]
您那边有没有确定模型的路径正确？并且选择的头文件正确吗？我最近抽会时间重新整理一下项目

**Comment by RichieMay** [comment]
路径这些都没问题 没明白说的头文件是什么呢 不知道你那边测试过模型冻结没
